from typing import List, Dict, Any
from datetime import datetime


def render_report(review: Dict, findings: List[Dict], patches: Dict[str, str], test_results: Dict[str, Dict]) -> str:
    """Render the final review report as Markdown."""
    
    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        severity_counts[f["severity"]] = severity_counts.get(f["severity"], 0) + 1
    
    blocking = severity_counts["critical"] + severity_counts["high"]
    verdict = "BLOCKED" if blocking > 0 else "PASSED"
    
    lines = [
        f"# ReviewGuard Report",
        f"",
        f"**PR:** {review.get('pr_url', 'Manual diff')}",
        f"**Diff:** +{review.get('lines_added', 0)} / -{review.get('lines_removed', 0)} ({review.get('files_changed', 0)} files)",
        f"**Verdict:** {verdict}",
        f"**Completed:** {datetime.utcnow().isoformat()}Z",
        f"",
        f"## Summary",
        f"",
        f"ReviewGuard analyzed this change with 5 parallel specialized subagents. "
        f"Found **{sum(severity_counts.values())} issues** "
        f"({severity_counts['critical']} Critical, {severity_counts['high']} High, "
        f"{severity_counts['medium']} Medium, {severity_counts['low']} Low, {severity_counts['info']} Info). "
        f"{'Merge blocked.' if blocking > 0 else 'No blocking issues.'}",
        f"",
        f"## Findings by Severity",
        f"",
    ]
    
    for severity in ["critical", "high", "medium", "low", "info"]:
        sev_findings = [f for f in findings if f["severity"] == severity]
        if not sev_findings:
            continue
        
        lines.append(f"### {severity.capitalize()} ({len(sev_findings)})")
        lines.append(f"")
        
        for f in sev_findings:
            patch_indicator = " 🔧" if f["file_path"] in patches else ""
            lines.append(f"- **{f['file_path']}:{f['line_start']}** [{f['category']}] {f['explanation'][:120]}{'...' if len(f['explanation']) > 120 else ''}{patch_indicator}")
        
        lines.append(f"")
    
    if patches:
        lines.append(f"## Suggested Patches")
        lines.append(f"")
        for file_path, patch in patches.items():
            lines.append(f"### `{file_path}`")
            lines.append(f"")
            lines.append(f"```diff")
            lines.append(patch)
            lines.append(f"```")
            lines.append(f"")
    
    if test_results:
        lines.append(f"## Test Verification")
        lines.append(f"")
        for file_path, result in test_results.items():
            status = "✅ PASSED" if result.get("tests_failed", 1) == 0 else "❌ FAILED"
            lines.append(f"- **{file_path}**: {status} ({result.get('tests_passed', 0)} passed, {result.get('tests_failed', 0)} failed)")
            if result.get("failure_detail"):
                lines.append(f"  - Failure: {result['failure_detail'][:200]}...")
        lines.append(f"")
    
    lines.append(f"---")
    lines.append(f"*Generated by ReviewGuard — IBM Bob Hackathon Track 3*")
    
    return "\n".join(lines)